### ISSUE TITLE
Uncaught TypeError: Cannot read property 'validate' of undefined at fuzzball.js:26

### ISSUE THREAD

**Issue by Oliverfk93916** [nol13/fuzzball.js#11]
Hi, 

I'm working in Svelte and my line is simply:

import fuzzball from 'fuzzball'

In the console, I'm getting the error in the title and I'm not sure why.

Thes are lines 25 and 26 and 26 is where the error stems from

25: var utils = require('./lib/utils.js')(_uniq, _uniqWith, _partialRight)
26: var validate = utils.validate

**Comment by nol13** [comment]
Hmm, ya Rollup seems to be having an issue with the function export from utils, not sure if this is a bug in Rollup or possibly a config issue. Or if they're somehow being more strict about something than other build systems and it could be addressed from this end.

Importing from the pre-built umd file instead of the normal entry point seems to work fine though. I tried this using the default svelte template from their site and it ran ok.

import fuzzball from 'fuzzball/dist/fuzzball.umd.min.js'

**Comment by Oliverfk93916** [comment]
Oh dear, I feel so dumb for not trying that... 

Thank you man!

**Comment by nol13** [comment]
No prob. Usually shouldn't need to use that if you're using a bundler already, but it'll work.

Looking into it further I think this issue is actually how Rollup handles the line above that one, it has an issue with the conditional require and doesn't transform it properly. It strips or hoists the require, but leaves the if statement with invalid syntax if it doesn't have brackets.

Changing it from..
if(condition) require('stuff')
to..
if(condition) { require('stuff') }

in the fuzzball code seems to fix it as well. So a Rollup transform bug somewhere causing it, but it's easy enough to add the brackets too. I'll push up a patch for it in a bit.
